### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by athursto** [camillawilliams/puzzleproject#1]
As a user, I can log into my account in the app
[to access the puzzles]

**Comment by athursto** [comment]
@Carmi1234 this works now?

**Comment by Carmi1234** [comment]
> @Carmi1234 this works now?

yeah it should work.

**Comment by athursto** [comment]
need to add log out to count this as closed

**Comment by Carmi1234** [comment]
login and logout are complete.

**Comment by Carmi1234** [comment]
One final thing I need to do is create the ->  forgot username/password? option
